mini_batch_size: 64
epsilon_init: 1.0
epsilon_decay: 0.9995
network_sync_rate: 50
learning_rate: 0.0001
discount_factor: 0.99
fc1_nodes: 64
enable_double_dqn: True
enable_dueling_dqn: True
total_steps_per_episode: 10000
total_episodes: 1000
min_epsilon: 0.02
show_every: 50
render: True
fc_dueling: 64